-   id: flutter-format
    name: Format Flutter Code
    entry: flutter
    language: script
    files: lib integration_test
-   id: dart-fix
    name: Fix Dart Code
    entry: dart
    language: script
    files: lib integration_test
